#!/bin/bash

exec 2>&1

while true; do
  echo "Starting compliance scan"
  inspec exec --config {{pkg.svc_config_path}}/config.json {{pkg.path}}/inspec_demo

  echo "Sleeping for {{cfg.a2.sleep}} seconds"
  sleep {{cfg.a2.sleep}}
done
